name: Generate Metrics

on:
  schedule:
    - cron: "5 4 * * 6"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_traffic: yes
